// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dec_exec.proto

package dotspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName  string   `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppUid   int64    `protobuf:"varint,2,opt,name=app_uid,json=appUid,proto3" json:"app_uid,omitempty"`
	FuncName string   `protobuf:"bytes,3,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	InFiles  []string `protobuf:"bytes,4,rep,name=in_files,json=inFiles,proto3" json:"in_files,omitempty"`
	OutFiles []string `protobuf:"bytes,5,rep,name=out_files,json=outFiles,proto3" json:"out_files,omitempty"`
	ClientId string   `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dec_exec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_dec_exec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_dec_exec_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *App) GetAppUid() int64 {
	if x != nil {
		return x.AppUid
	}
	return 0
}

func (x *App) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *App) GetInFiles() []string {
	if x != nil {
		return x.InFiles
	}
	return nil
}

func (x *App) GetOutFiles() []string {
	if x != nil {
		return x.OutFiles
	}
	return nil
}

func (x *App) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Blob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val      []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *Blob) Reset() {
	*x = Blob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dec_exec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_dec_exec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_dec_exec_proto_rawDescGZIP(), []int{1}
}

func (x *Blob) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Blob) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Blob) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dec_exec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_dec_exec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_dec_exec_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_dec_exec_proto protoreflect.FileDescriptor

var file_dec_exec_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x65, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x22, 0xab, 0x01, 0x0a, 0x03, 0x41,
	0x70, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x70, 0x70, 0x55, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x62,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x76, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x98, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x45, 0x78, 0x65, 0x63, 0x12,
	0x29, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x0d, 0x2e, 0x64, 0x65, 0x63, 0x5f, 0x65, 0x78,
	0x65, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x1a, 0x10, 0x2e, 0x64, 0x65, 0x63, 0x5f, 0x65, 0x78, 0x65,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0e, 0x2e, 0x64, 0x65, 0x63, 0x5f, 0x65,
	0x78, 0x65, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x1a, 0x10, 0x2e, 0x64, 0x65, 0x63, 0x5f, 0x65,
	0x78, 0x65, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0c,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0e, 0x2e, 0x64,
	0x65, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x1a, 0x0e, 0x2e, 0x64,
	0x65, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x22, 0x00, 0x42, 0x2f,
	0x0a, 0x17, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x64, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x2e, 0x64, 0x65, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x42, 0x0c, 0x44, 0x65, 0x63, 0x45, 0x78,
	0x65, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0xa2, 0x02, 0x03, 0x44, 0x54, 0x45, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dec_exec_proto_rawDescOnce sync.Once
	file_dec_exec_proto_rawDescData = file_dec_exec_proto_rawDesc
)

func file_dec_exec_proto_rawDescGZIP() []byte {
	file_dec_exec_proto_rawDescOnce.Do(func() {
		file_dec_exec_proto_rawDescData = protoimpl.X.CompressGZIP(file_dec_exec_proto_rawDescData)
	})
	return file_dec_exec_proto_rawDescData
}

var file_dec_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dec_exec_proto_goTypes = []interface{}{
	(*App)(nil),    // 0: dec_exec.App
	(*Blob)(nil),   // 1: dec_exec.Blob
	(*Result)(nil), // 2: dec_exec.Result
}
var file_dec_exec_proto_depIdxs = []int32{
	0, // 0: dec_exec.DecExec.Exec:input_type -> dec_exec.App
	1, // 1: dec_exec.DecExec.UploadBlob:input_type -> dec_exec.Blob
	1, // 2: dec_exec.DecExec.RetrieveBlob:input_type -> dec_exec.Blob
	2, // 3: dec_exec.DecExec.Exec:output_type -> dec_exec.Result
	2, // 4: dec_exec.DecExec.UploadBlob:output_type -> dec_exec.Result
	1, // 5: dec_exec.DecExec.RetrieveBlob:output_type -> dec_exec.Blob
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dec_exec_proto_init() }
func file_dec_exec_proto_init() {
	if File_dec_exec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dec_exec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dec_exec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dec_exec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dec_exec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dec_exec_proto_goTypes,
		DependencyIndexes: file_dec_exec_proto_depIdxs,
		MessageInfos:      file_dec_exec_proto_msgTypes,
	}.Build()
	File_dec_exec_proto = out.File
	file_dec_exec_proto_rawDesc = nil
	file_dec_exec_proto_goTypes = nil
	file_dec_exec_proto_depIdxs = nil
}
